import {
  IconChartBar,
  IconDashboard,
  IconUsers,
  IconMessage,
  IconPhone,
  IconStar,
  IconLibraryFilled,
  IconBook,
  IconRosetteDiscountFilled,
  IconCashMoveBack,
  IconBrandMetabrainz,
  IconListTree,
  IconScript,
  IconQuestionMark,
  IconWorld,
  IconPlayerPlay,
  IconAlignBoxBottomCenter,
  IconSend,
  IconBuildingStore,
  IconBell,
  IconMapQuestion,
  IconNotes,
  IconHistory,
} from "@tabler/icons-react";

export const data = {
  navMain: [
    {
      title: "Overview",
      url: "/dashboard/overview",
      icon: IconDashboard,
      permission: { resource: "dashboard", action: "get" },
      roles: ["owner", "admin"],
    },
    {
      title: "Analytics",
      url: "/dashboard/analytics",
      icon: IconChartBar,
      permission: { resource: "analytics", action: "get" },
      roles: ["owner", "admin", "member"],
    },
    {
      title: "Users",
      url: "/dashboard/users",
      icon: IconUsers,
      permission: { resource: "users", action: "get" },
      roles: ["owner", "admin", "member"],
    },
    {
      title: "Members",
      url: "/dashboard/members",
      icon: IconUsers,
      permission: { resource: "people", action: "get" },
      roles: ["owner", "admin", "member"],
    },
    {
      title: "Chats",
      url: "/dashboard/chats",
      icon: IconMessage,
      permission: { resource: "chat", action: "get" },
      roles: ["owner", "admin", "member"],
    },
    {
      title: "Audio Calls",
      url: "/dashboard/calls",
      icon: IconPhone,
      permission: { resource: "call", action: "get" },
      roles: ["owner", "admin", "member"],
    },
    {
      title: "Reviews",
      url: "/dashboard/reviews",
      icon: IconStar,
      permission: { resource: "review", action: "get" },
      roles: ["owner", "admin", "member"],
    },
    {
      title: "Courses",
      icon: IconLibraryFilled,
      permission: { resource: "course", action: "get" },
      roles: ["owner", "admin", "member"],
      subMenu: [
        {
          title: "My Courses",
          url: "/dashboard/courses/my-courses",
          icon: IconBook,
          permission: { resource: "course", action: "get" },
          roles: ["owner", "admin", "member"],
        },
        {
          title: "Coupon",
          url: "/dashboard/courses/coupon",
          icon: IconRosetteDiscountFilled,
          permission: { resource: "coupon", action: "get" },
          roles: ["owner", "admin", "member"],
        },
        {
          title: "Backend Addition",
          url: "/dashboard/courses/ba",
          icon: IconCashMoveBack,
          permission: { resource: "course", action: "get" },
          roles: ["owner", "admin", "member"],
        },
      ],
    },
    {
      title: "Platform",
      icon: IconBrandMetabrainz,
      permission: { resource: "platform", action: "get" },
      roles: ["owner", "admin", "member"],
      subMenu: [
        {
          title: "Policies",
          url: "/dashboard/platform/policy",
          icon: IconScript,
          permission: { resource: "platform", action: "get" },
          roles: ["owner", "admin", "member"],
        },
        {
          title: "Faqs",
          url: "/dashboard/platform/faqs",
          icon: IconQuestionMark,
          permission: { resource: "platform", action: "get" },
          roles: ["owner", "admin", "member"],
        },
      ],
    },
    {
      title: "Community",
      icon: IconWorld,
      permission: { resource: "community", action: "get" },
      roles: ["owner", "admin", "member"],
      subMenu: [
        {
          title: "Shorts",
          url: "/dashboard/community/shorts",
          icon: IconPlayerPlay,
          permission: { resource: "community", action: "get" },
          roles: ["owner", "admin", "member"],
        },
        {
          title: "Polls",
          url: "/dashboard/community/polls",
          icon: IconAlignBoxBottomCenter,
          permission: { resource: "community", action: "get" },
          roles: ["owner", "admin", "member"],
        },
        {
          title: "Post",
          url: "/dashboard/community/post",
          icon: IconSend,
          permission: { resource: "community", action: "get" },
          roles: ["owner", "admin", "member"],
        },
      ],
    },
    {
      title: "Marketing",
      icon: IconBuildingStore,
      permission: { resource: "marketing", action: "get" },
      roles: ["owner", "admin", "member"],
      subMenu: [
        {
          title: "Banner",
          url: "/dashboard/marketing/banner",
          icon: IconListTree,
          permission: { resource: "marketing", action: "get" },
          roles: ["owner", "admin", "member"],
        },
        {
          title: "Notification",
          url: "/dashboard/marketing/notification",
          icon: IconBell,
          permission: { resource: "marketing", action: "get" },
          roles: ["owner", "admin", "member"],
        },
        {
          title: "Quest",
          url: "/dashboard/marketing/quest",
          icon: IconMapQuestion,
          permission: { resource: "marketing", action: "get" },
          roles: ["owner", "admin", "member"],
        },
      ],
    },
    {
      title: "Test Portal",
      icon: IconNotes,
      permission: { resource: "testPortal", action: "get" },
      roles: ["owner", "admin", "member"],
      subMenu: [
        {
          title: "Questions",
          url: "/dashboard/test-portal/questions",
          icon: IconMapQuestion,
          permission: { resource: "testPortal", action: "get" },
          roles: ["owner", "admin", "member"],
        },
        {
          title: "Test History",
          url: "/dashboard/test-portal/history",
          icon: IconHistory,
          permission: { resource: "testPortal", action: "get" },
          roles: ["owner", "admin", "member"],
        },
      ],
    },
  ],
};
